[functions.create-rider]
verify_jwt = false


[functions.create-paymongo-checkout]
verify_jwt = false

[functions.paymongo-webhook]
verify_jwt = false


[functions.calculate-delivery-route]
verify_jwt = false
[functions.system-admin-delete-restaurant]
verify_jwt = true
