import { useEffect, useMemo, useState } from 'react';
import { getRestaurantOrders, type RestaurantOrder } from '../services/restaurantOrderRepository';
import { supabase } from '../services/supabaseClient';

type Props = { restaurantId: string };
function isToday(dateString: string) { const date = new Date(dateString); const now = new Date(); return date.getFullYear() === now.getFullYear() && date.getMonth() === now.getMonth() && date.getDate() === now.getDate(); }
export function RestaurantDashboardPage({ restaurantId }: Props) {
  const [orders, setOrders] = useState<RestaurantOrder[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [realtimeStatus, setRealtimeStatus] = useState<'connecting' | 'live' | 'error'>('connecting');
  async function loadOrders() { try { setError(''); setOrders(await getRestaurantOrders(restaurantId)); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to load dashboard data.'); } finally { setLoading(false); } }
  useEffect(() => { void loadOrders(); const client = supabase; if (!client) { setRealtimeStatus('error'); return; } const channel = client.channel(`restaurant-orders:${restaurantId}`).on('broadcast', { event: 'restaurant_order_changed' }, () => { void loadOrders(); }).subscribe((status) => { if (status === 'SUBSCRIBED') setRealtimeStatus('live'); else if (status === 'CHANNEL_ERROR' || status === 'TIMED_OUT' || status === 'CLOSED') setRealtimeStatus('error'); }); return () => { void client.removeChannel(channel); }; }, [restaurantId]);
  const todayOrders = useMemo(() => orders.filter((order) => isToday(order.createdAt)), [orders]); const todaySales = useMemo(() => todayOrders.filter((order) => order.status === 'completed').reduce((sum, order) => sum + order.total, 0), [todayOrders]); const shippingFees = useMemo(() => todayOrders.reduce((sum, order) => sum + (order.shippingFee ?? 0), 0), [todayOrders]); const base = import.meta.env.BASE_URL.replace(/\/$/, '');
  return (<section className="restaurant-dashboard-page"><div className="restaurant-dashboard-header"><div><p className="eyebrow">Restaurant operations</p><h1>Dashboard</h1></div><span className={`restaurant-dashboard-live-status is-${realtimeStatus}`} aria-live="polite"><span className="restaurant-dashboard-live-dot" aria-hidden="true" />{realtimeStatus === 'live' ? 'Live' : realtimeStatus === 'connecting' ? 'Connecting…' : 'Reconnecting…'}</span></div><nav className="restaurant-dashboard-nav" aria-label="Restaurant navigation"><a className="is-active" href={`${base}/#restaurant/dashboard`}>Dashboard</a><a href={`${base}/#restaurant/orders`}>Orders</a><a href={`${base}/#restaurant/menu`}>Product</a></nav>{error && <div className="restaurant-dashboard-error" role="alert">{error}</div>}{loading ? <div className="restaurant-dashboard-empty">Loading dashboard…</div> : <div className="restaurant-dashboard-stats"><a className="restaurant-dashboard-stat" href={`${base}/#restaurant/orders`}><span>Orders</span><strong>{todayOrders.length}</strong><small>Today's orders</small></a><a className="restaurant-dashboard-stat" href={`${base}/#restaurant/menu`}><span>Product</span><strong>Menu</strong><small>Manage your menu</small></a><article className="restaurant-dashboard-stat"><span>Shipping fee</span><strong>₱{shippingFees.toFixed(2)}</strong><small>Today's delivery fees</small></article><article className="restaurant-dashboard-stat"><span>Sales</span><strong>₱{todaySales.toFixed(2)}</strong><small>Completed sales today</small></article></div>}</section>);
}