import { useEffect, useMemo, useState } from 'react';
import { getRestaurantOrders, type RestaurantOrder } from '../services/restaurantOrderRepository';
import { getRestaurantShippingFee, updateRestaurantShippingFee } from '../services/restaurantSettingsRepository';
import { supabase } from '../services/supabaseClient';

type Props = { restaurantId: string };
function isToday(dateString: string) { const date = new Date(dateString); const now = new Date(); return date.getFullYear() === now.getFullYear() && date.getMonth() === now.getMonth() && date.getDate() === now.getDate(); }

export function RestaurantDashboardPage({ restaurantId }: Props) {
  const [orders, setOrders] = useState<RestaurantOrder[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [realtimeStatus, setRealtimeStatus] = useState<'connecting' | 'live' | 'error'>('connecting');
  const [shippingFee, setShippingFee] = useState(0); const [shippingFeeInput, setShippingFeeInput] = useState('0'); const [savingShippingFee, setSavingShippingFee] = useState(false); const [shippingFeeMessage, setShippingFeeMessage] = useState('');

  async function loadOrders() { try { setError(''); setOrders(await getRestaurantOrders(restaurantId)); } catch (err) { setError(err instanceof Error ? err.message : 'Unable to load dashboard data.'); } finally { setLoading(false); } }
  async function loadShippingFee() { try { const fee = await getRestaurantShippingFee(restaurantId); setShippingFee(fee); setShippingFeeInput(String(fee)); } catch (err) { setShippingFeeMessage(err instanceof Error ? err.message : 'Unable to load shipping fee.'); } }
  async function handleSaveShippingFee() { const fee = Number(shippingFeeInput); if (!Number.isFinite(fee) || fee < 0) { setShippingFeeMessage('Enter a valid shipping fee of ₱0 or more.'); return; } setSavingShippingFee(true); setShippingFeeMessage(''); try { await updateRestaurantShippingFee(restaurantId, Math.round(fee * 100) / 100); setShippingFee(Math.round(fee * 100) / 100); setShippingFeeInput(String(Math.round(fee * 100) / 100)); setShippingFeeMessage('Shipping fee saved.'); } catch (err) { setShippingFeeMessage(err instanceof Error ? err.message : 'Unable to save shipping fee.'); } finally { setSavingShippingFee(false); } }

  useEffect(() => { void loadOrders(); void loadShippingFee(); const client = supabase; if (!client) { setRealtimeStatus('error'); return; } const channel = client.channel(`restaurant-orders:${restaurantId}`).on('broadcast', { event: 'restaurant_order_changed' }, () => { void loadOrders(); }).subscribe((status) => { if (status === 'SUBSCRIBED') setRealtimeStatus('live'); else if (status === 'CHANNEL_ERROR' || status === 'TIMED_OUT' || status === 'CLOSED') setRealtimeStatus('error'); }); return () => { void client.removeChannel(channel); }; }, [restaurantId]);

  const todayOrders = useMemo(() => orders.filter((order) => isToday(order.createdAt)), [orders]); const todaySales = useMemo(() => todayOrders.filter((order) => order.status === 'completed').reduce((sum, order) => sum + order.total, 0), [todayOrders]);
  return (<section className="restaurant-dashboard-page"><div className="restaurant-dashboard-header"><div><p className="eyebrow">Restaurant operations</p><h1>Dashboard</h1></div><span className={`restaurant-dashboard-live-status is-${realtimeStatus}`} aria-live="polite"><span className="restaurant-dashboard-live-dot" aria-hidden="true" />{realtimeStatus === 'live' ? 'Live' : realtimeStatus === 'connecting' ? 'Connecting…' : 'Reconnecting…'}</span></div>{error && <div className="restaurant-dashboard-error" role="alert">{error}</div>}{loading ? <div className="restaurant-dashboard-empty">Loading dashboard…</div> : <div className="restaurant-dashboard-stats"><a className="restaurant-dashboard-stat" href="#restaurant/orders"><span>Orders</span><strong>{todayOrders.length}</strong><small>Today's orders</small></a><a className="restaurant-dashboard-stat" href="#restaurant/menu"><span>Product</span><strong>Menu</strong><small>Manage your menu</small></a><article className="restaurant-dashboard-stat"><span>Shipping fee</span><strong>₱{shippingFee.toFixed(2)}</strong><small>Set your delivery fee</small><div className="restaurant-shipping-fee-editor"><label htmlFor="restaurant-shipping-fee">Delivery fee</label><div><span>₱</span><input id="restaurant-shipping-fee" type="number" min="0" step="0.01" inputMode="decimal" value={shippingFeeInput} onChange={(event) => { setShippingFeeInput(event.target.value); setShippingFeeMessage(''); }} /><button type="button" onClick={() => void handleSaveShippingFee()} disabled={savingShippingFee}>{savingShippingFee ? 'Saving…' : 'Save'}</button></div>{shippingFeeMessage && <small role="status">{shippingFeeMessage}</small>}</div></article><article className="restaurant-dashboard-stat"><span>Sales</span><strong>₱{todaySales.toFixed(2)}</strong><small>Completed sales today</small></article></div>}</section>);
}
