import { useEffect, useState } from 'react';
import { supabase } from '../services/supabaseClient';

type Props={restaurantId:string};
type Address={line1:string;line2:string;city:string;state:string;country:string;postal_code:string};
type Person={first_name:string;last_name:string;middle_name:string;mobile_number:string;email_address:string;date_of_birth:{day:number;month:number;year:number};nationality:string;nature_of_work:string;place_of_birth:{city:string;country:string};source_of_funds:string;source_of_funds_other:string;source_of_funds_salary:string;tin:string;address:Address};
type Business={trade_name:string;legal_name:string;dti_registered_name:string;type:string;tin:string;industry:string;description:string;age:string;size:string;estimated_monthly_volume:string;physical_store:boolean;customer_service_number:string;website:string;address:Address};
const address=():Address=>({line1:'',line2:'',city:'',state:'',country:'PH',postal_code:''});
const person=():Person=>({first_name:'',last_name:'',middle_name:'',mobile_number:'',email_address:'',date_of_birth:{day:1,month:1,year:1990},nationality:'PHL',nature_of_work:'self_employed',place_of_birth:{city:'',country:'PH'},source_of_funds:'other',source_of_funds_other:'',source_of_funds_salary:'',tin:'',address:address()});
const business=():Business=>({trade_name:'',legal_name:'',dti_registered_name:'',type:'sole_proprietor',tin:'',industry:'5812',description:'Restaurant food and beverage business',age:'less_than_1_year',size:'less_than_10',estimated_monthly_volume:'less_than_100K',physical_store:true,customer_service_number:'',website:'',address:address()});
function merge<T extends object>(a:T,v:unknown):T{return !v||typeof v!=='object'?a:{...a,...(v as Partial<T>)};}

export function PayMongoLiveOnboardingCard({restaurantId}:Props){
 const [status,setStatus]=useState('not_connected'),[accountId,setAccountId]=useState(''),[step,setStep]=useState(''),[identity,setIdentity]=useState(''),[verificationUrl,setVerificationUrl]=useState('');
 const [p,setP]=useState<Person>(person()),[b,setB]=useState<Business>(business()),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 async function load(){if(!supabase)return;const{data,error:e}=await supabase.from('restaurant_paymongo_accounts').select('connection_status,paymongo_account_id,verification_url,identity_verification_status,onboarding_step,onboarding_data').eq('restaurant_id',restaurantId).eq('environment','live').maybeSingle();if(e){setError(e.message);return}setStatus(data?.connection_status??'not_connected');setAccountId(data?.paymongo_account_id??'');setVerificationUrl(data?.verification_url??'');setStep(data?.onboarding_step??'');setIdentity(data?.identity_verification_status??'');const x=data?.onboarding_data&&typeof data.onboarding_data==='object'?data.onboarding_data as Record<string,unknown>:{};setP(merge(person(),x.person));setB(merge(business(),x.business));}
 useEffect(()=>{void load()},[restaurantId]);
 async function call(name:string,body:unknown){if(!supabase)throw new Error('Supabase is not configured.');const{data,error:e}=await supabase.functions.invoke(name,{body});if(e){const r=(e as {context?:Response}).context;const x=r?await r.clone().json().catch(()=>null):null;throw new Error(x?.error||e.message)}return data}
 async function start(){setBusy(true);setError('');try{const x=await call('create-paymongo-child-account',{restaurantId});setStatus(x?.status??'pending');setAccountId(x?.paymongoAccountId??'');setVerificationUrl(x?.verificationUrl??'');setStep(x?.onboardingStep??'identity_verification');if(x?.verificationUrl)window.open(x.verificationUrl,'_blank','noopener,noreferrer');setMessage('PayMongo live onboarding started. Complete identity verification first.')}catch(e){setError(e instanceof Error?e.message:'Unable to start PayMongo onboarding.')}finally{setBusy(false)}}
 async function refresh(){setBusy(true);setError('');try{const x=await call('sync-paymongo-child-account',{restaurantId});setStatus(x?.status??'pending');setAccountId(x?.paymongoAccountId??accountId);setVerificationUrl(x?.verificationUrl??verificationUrl);setStep(x?.onboardingStep??step);setIdentity(x?.identityVerificationStatus??identity);if(x?.account?.person)setP(v=>merge(v,x.account.person));if(x?.account?.business)setB(v=>merge(v,x.account.business));setMessage(x?.onboardingStep==='business_information'?'Identity verification passed. Complete merchant information, then save and activate.':x?.status==='active'?'PayMongo live account is active.':'PayMongo status: '+(x?.activationStatus??'in progress')+'.')}catch(e){setError(e instanceof Error?e.message:'Unable to refresh PayMongo status.')}finally{setBusy(false)}}
 async function save(){setBusy(true);setError('');try{const x=await call('update-paymongo-child-account',{restaurantId,person:p,business:b});if(x?.account?.person)setP(v=>merge(v,x.account.person));if(x?.account?.business)setB(v=>merge(v,x.account.business));setStep('activation');setMessage('Merchant information saved to PayMongo. Review it before activating.')}catch(e){setError(e instanceof Error?e.message:'Unable to save PayMongo merchant information.')}finally{setBusy(false)}}
 async function activate(){setBusy(true);setError('');try{const x=await call('activate-paymongo-child-account',{restaurantId});setMessage(x?.message??'Activation submitted. Refresh the status after PayMongo processes the account.');await refresh()}catch(e){setError(e instanceof Error?e.message:'Unable to activate PayMongo merchant account.')}finally{setBusy(false)}}
 const f=(label:string,value:string,on:(v:string)=>void,req=false,type='text')=><label className="restaurant-settings-field"><span>{label}</span><input type={type} value={value} required={req} disabled={busy||status==='active'} onChange={e=>on(e.target.value)}/></label>;
 const a=(title:string,v:Address,on:(x:Address)=>void)=><div className="restaurant-paymongo-address"><strong>{title}</strong>{f('Address line 1',v.line1,x=>on({...v,line1:x}),true)}{f('Address line 2',v.line2,x=>on({...v,line2:x}))}{f('City',v.city,x=>on({...v,city:x}),true)}{f('State / province',v.state,x=>on({...v,state:x}),true)}{f('Postal code',v.postal_code,x=>on({...v,postal_code:x}),true)}</div>;
 const dob=String(p.date_of_birth.year)+'-'+String(p.date_of_birth.month).padStart(2,'0')+'-'+String(p.date_of_birth.day).padStart(2,'0');
 return <div className="restaurant-settings-card restaurant-paymongo-card">{error&&<div className="restaurant-paymongo-error"><strong>PayMongo onboarding error</strong><span>{error}</span></div>}{message&&<div className="restaurant-shipping-message is-success">{message}</div>}
 <h2>PayMongo Production Payments</h2><p className="restaurant-settings-help">Each restaurant gets its own PayMongo merchant account under Web2Table's parent account. The restaurant owner never gives Web2Table a PayMongo secret key.</p>
 <div className="restaurant-paymongo-status"><div><strong>Live environment</strong><span className={'restaurant-paymongo-badge is-'+status}>{status.replace('_',' ')}</span></div>{accountId&&<small>Connected account: {accountId}</small>}<small>Onboarding step: {step||'not started'}</small>{identity&&<small>Identity verification: {identity.replaceAll('_',' ')}</small>}</div>
 {status==='not_connected'&&<button type="button" className="button button-primary" disabled={busy} onClick={()=>void start()}>{busy?'Starting…':'Start Live Onboarding'}</button>}
 {verificationUrl&&identity!=='passed'&&identity!=='passed_attestation_form'&&<a className="button button-secondary" href={verificationUrl} target="_blank" rel="noreferrer">Open PayMongo Verification</a>}
 {accountId&&status!=='active'&&<><div className="restaurant-paymongo-onboarding-section"><h3>Authorized representative</h3><div className="restaurant-paymongo-grid">
 {f('First name',p.first_name,x=>setP({...p,first_name:x}),true)}{f('Middle name',p.middle_name,x=>setP({...p,middle_name:x}))}{f('Last name',p.last_name,x=>setP({...p,last_name:x}),true)}{f('Mobile number',p.mobile_number,x=>setP({...p,mobile_number:x}),true)}{f('Email address',p.email_address,x=>setP({...p,email_address:x}),true,'email')}{f('TIN',p.tin,x=>setP({...p,tin:x}),true)}{f('Date of birth',dob,x=>{const z=x.split('-').map(Number);if(z.length===3)setP({...p,date_of_birth:{year:z[0],month:z[1],day:z[2]}})},true,'date')}{f('Place of birth city',p.place_of_birth.city,x=>setP({...p,place_of_birth:{...p.place_of_birth,city:x}}),true)}{f('Nature of work',p.nature_of_work,x=>setP({...p,nature_of_work:x}),true)}{f('Source of funds',p.source_of_funds,x=>setP({...p,source_of_funds:x}),true)}{p.source_of_funds==='other'&&f('Source of funds details',p.source_of_funds_other,x=>setP({...p,source_of_funds_other:x}),true)}{p.source_of_funds==='salary'&&f('Employer / company',p.source_of_funds_salary,x=>setP({...p,source_of_funds_salary:x}),true)}</div>{a('Current address',p.address,x=>setP({...p,address:x}))}</div>
 <div className="restaurant-paymongo-onboarding-section"><h3>Business information</h3><div className="restaurant-paymongo-grid">{f('Trade name',b.trade_name,x=>setB({...b,trade_name:x}),true)}{f('Legal name',b.legal_name,x=>setB({...b,legal_name:x}),true)}{f('DTI registered name',b.dti_registered_name,x=>setB({...b,dti_registered_name:x))}{f('Business TIN',b.tin,x=>setB({...b,tin:x}),true)}{f('Industry MCC',b.industry,x=>setB({...b,industry:x}),true)}{f('Business description',b.description,x=>setB({...b,description:x}),true)}{f('Customer service number',b.customer_service_number,x=>setB({...b,customer_service_number:x}),true)}{f('Website',b.website,x=>setB({...b,website:x}))}{f('Business type',b.type,x=>setB({...b,type:x}),true)}{f('Business age',b.age,x=>setB({...b,age:x}),true)}{f('Business size',b.size,x=>setB({...b,size:x}),true)}{f('Estimated monthly volume',b.estimated_monthly_volume,x=>setB({...b,estimated_monthly_volume:x}),true)}</div>{a('Business address',b.address,x=>setB({...b,address:x}))}</div>
 <div className="restaurant-paymongo-actions"><button type="button" className="button button-primary" disabled={busy} onClick={()=>void save()}>{busy?'Saving…':'Save Merchant Information'}</button><button type="button" className="button button-secondary" disabled={busy} onClick={()=>void activate()}>Activate PayMongo Account</button><button type="button" className="button button-secondary" disabled={busy} onClick={()=>void refresh()}>{busy?'Checking…':'Refresh Live Status'}</button></div>
 </>}
 {status==='active'&&<div className="restaurant-paymongo-actions"><button type="button" className="button button-secondary" disabled={busy} onClick={()=>void refresh()}>{busy?'Checking…':'Refresh Live Status'}</button></div>}
 <style>{'.restaurant-paymongo-onboarding-section{margin-top:18px;padding-top:18px;border-top:1px solid #e2e8f0}.restaurant-paymongo-onboarding-section h3{margin:0 0 12px;font-size:16px;color:#0f172a}.restaurant-paymongo-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.restaurant-paymongo-address{margin-top:14px;display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.restaurant-paymongo-address>strong{grid-column:1/-1;color:#334155;font-size:13px}@media(max-width:700px){.restaurant-paymongo-grid,.restaurant-paymongo-address{grid-template-columns:1fr}}'}</style></div>;
}