-- DEPRECATED LEGACY SCRIPT — DO NOT RUN.
-- Riders are employees stored in public.restaurant_staff with role = 'rider'.
-- The historical migration 0048_unify_rider_delivery_references.sql migrates
-- delivery references to restaurant_staff and removes public.restaurant_riders.
-- This file is retained only for repository history; it intentionally contains
-- no executable DDL that creates a second rider table.
--
-- Current rider delivery scopes, if used, must reference the unified staff id:
--   rider_delivery_zones.rider_id -> public.restaurant_staff.id
-- Enforce role = 'rider' and matching restaurant_id in the applicable policies.
