-- Persistent per-client rate limit for public delivery-route calculations.
-- Store only a SHA-256 key generated by the Edge Function, not raw IP addresses.
create table if not exists public.delivery_route_rate_limits (
  rate_limit_key text primary key,
  window_started_at timestamptz not null,
  request_count integer not null default 0 check (request_count >= 0),
  updated_at timestamptz not null default now()
);

create index if not exists idx_delivery_route_rate_limits_updated_at
  on public.delivery_route_rate_limits (updated_at);

alter table public.delivery_route_rate_limits enable row level security;
revoke all on table public.delivery_route_rate_limits from public, anon, authenticated;
grant all on table public.delivery_route_rate_limits to service_role;

create or replace function public.consume_delivery_route_rate_limit(p_rate_limit_key text)
returns boolean
language plpgsql
security definer
set search_path = public, pg_temp
as $function$
declare
  v_request_count integer;
begin
  if p_rate_limit_key is null or length(p_rate_limit_key) <> 64
     or p_rate_limit_key !~ '^[0-9a-f]{64}$' then
    return false;
  end if;

  insert into public.delivery_route_rate_limits (
    rate_limit_key, window_started_at, request_count, updated_at
  )
  values (p_rate_limit_key, clock_timestamp(), 1, clock_timestamp())
  on conflict (rate_limit_key) do update
    set window_started_at = case
          when public.delivery_route_rate_limits.window_started_at <= clock_timestamp() - interval '1 minute'
            then clock_timestamp()
          else public.delivery_route_rate_limits.window_started_at
        end,
        request_count = case
          when public.delivery_route_rate_limits.window_started_at <= clock_timestamp() - interval '1 minute'
            then 1
          else public.delivery_route_rate_limits.request_count + 1
        end,
        updated_at = clock_timestamp()
  returning request_count into v_request_count;

  -- Opportunistic cleanup prevents stale client keys accumulating indefinitely.
  delete from public.delivery_route_rate_limits
  where updated_at < clock_timestamp() - interval '1 day';

  return v_request_count <= 12;
end;
$function$;

revoke all on function public.consume_delivery_route_rate_limit(text) from public, anon, authenticated;
grant execute on function public.consume_delivery_route_rate_limit(text) to service_role;
